# Generated by Django 5.0.2 on 2024-03-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0004_usuario_remove_factura_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipo',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
