# Generated by Django 5.0.2 on 2024-03-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0005_producto_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='usuario',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
