# Generated by Django 5.0.2 on 2024-03-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0006_usuario_password_usuario_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='detallecarrito',
            name='carrito',
        ),
        migrations.RemoveField(
            model_name='detallecarrito',
            name='producto',
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
        migrations.DeleteModel(
            name='DetalleCarrito',
        ),
    ]
